import streamlit as st
import pandas as pd
import joblib

saved_model = joblib.load("models/house_price_model.pkl")

model = saved_model["model"]
features = saved_model["features"]

with st.expander("🏠 House Information", expanded=True):

    bedrooms = st.number_input(
        "Bedrooms",
        min_value=0.0,
        value=3.0,
        step=1.0
    )

    bathrooms = st.number_input(
        "Bathrooms",
        min_value=0.0,
        value=2.0,
        step=0.25
    )

    floors = st.number_input(
        "Floors",
        min_value=1.0,
        value=1.0,
        step=0.5
    )

    sqft_living = st.number_input(
        "Living Area (sqft)",
        min_value=0,
        value=2000,
        step=100
    )

    sqft_lot = st.number_input(
        "Lot Area (sqft)",
        min_value=0,
        value=5000,
        step=500
    )

with st.expander("⭐ House Quality"):

    grade = st.slider(
        "House Grade",
        min_value=1,
        max_value=13,
        value=7
    )

    condition = st.slider(
        "Condition",
        min_value=1,
        max_value=5,
        value=3
    )

    view = st.slider(
        "View Quality",
        min_value=0,
        max_value=4,
        value=0
    )

    waterfront = st.selectbox(
        "Waterfront",
        ["No", "Yes"]
    )

    waterfront = 1 if waterfront == "Yes" else 0

    waterfront = 1 if waterfront == "Yes" else 0

with st.expander("🏗️ House Structure"):

    sqft_above = st.number_input(
        "Above-Ground Area (sqft)",
        min_value=0,
        value=1500,
        step=100
    )

    sqft_basement = st.number_input(
        "Basement Area (sqft)",
        min_value=0,
        value=500,
        step=100
    )

    sqft_living15 = st.number_input(
        "Average Living Area of Nearby Houses (sqft)",
        min_value=0,
        value=2000,
        step=100
    )

    sqft_lot15 = st.number_input(
        "Average Lot Area of Nearby Houses (sqft)",
        min_value=0,
        value=5000,
        step=500
    )

with st.expander("📍 Location & Age"):

    yr_built = st.number_input(
        "Year Built",
        min_value=1800,
        max_value=2026,
        value=1990,
        step=1
    )

    yr_renovated = st.number_input(
        "Year Renovated (0 if never renovated)",
        min_value=0,
        max_value=2026,
        value=0,
        step=1
    )

    zipcode = st.number_input(
        "ZIP Code",
        min_value=0,
        value=98001,
        step=1
    )

    lat = st.number_input(
        "Latitude",
        value=47.5,
        format="%.4f"
    )

    long = st.number_input(
        "Longitude",
        value=-122.2,
        format="%.4f"
    )

with st.expander("📅 Sale Information"):

    year = st.number_input(
        "Sale Year",
        min_value=2014,
        max_value=2015,
        value=2014,
        step=1
    )

    month = st.slider(
        "Sale Month",
        min_value=1,
        max_value=12,
        value=6
    )

st.divider()

if st.button("Predict House Price"):

    house_data = pd.DataFrame([{
        "bedrooms": bedrooms,
        "bathrooms": bathrooms,
        "sqft_living": sqft_living,
        "sqft_lot": sqft_lot,
        "floors": floors,
        "waterfront": waterfront,
        "view": view,
        "condition": condition,
        "grade": grade,
        "sqft_above": sqft_above,
        "sqft_basement": sqft_basement,
        "yr_built": yr_built,
        "yr_renovated": yr_renovated,
        "zipcode": zipcode,
        "lat": lat,
        "long": long,
        "sqft_living15": sqft_living15,
        "sqft_lot15": sqft_lot15,
        "year": year,
        "month": month
    }])

    house_data = house_data[features]

    prediction = model.predict(house_data)[0]

    st.subheader("🏠 Estimated House Price")

    st.metric(
        label="Predicted Price",
        value=f"${prediction:,.0f}"
    )

    st.caption(
        "This estimate is generated by the trained Random Forest model "
        "based on the information provided."
    )

    with st.expander("📊 Model Performance"):

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("R² Score", "0.881")

        with col2:
            st.metric("MAE", "$67,229")

        with col3:
            st.metric("RMSE", "$124,306")